package space.tokenpay.id.internal

import space.tokenpay.id.TpidConfig
import java.util.Locale

/**
 * Centralised UI strings for the native widget.
 * Resolves to the requested [TpidConfig.Language] with English as the fallback.
 * Keep keys in sync with Swift `Strings.swift` and JVM `Strings.kt`.
 */
internal object Strings {

    fun resolveLanguage(pref: TpidConfig.Language): TpidConfig.Language = when (pref) {
        TpidConfig.Language.SYSTEM -> when (Locale.getDefault().language) {
            "ru" -> TpidConfig.Language.RUSSIAN
            "zh" -> TpidConfig.Language.CHINESE
            else -> TpidConfig.Language.ENGLISH
        }
        else -> pref
    }

    fun of(lang: TpidConfig.Language): Map<String, String> = when (resolveLanguage(lang)) {
        TpidConfig.Language.RUSSIAN -> ru
        TpidConfig.Language.CHINESE -> zh
        else -> en
    }

    private val en = mapOf(
        "welcome_subtitle"       to "Unified identification system",
        "welcome_sign_in"        to "Sign in",
        "welcome_create"         to "Create account",
        "welcome_or"             to "or",
        "welcome_open_web"       to "Open tokenpay.space",
        "signin_title"           to "Sign in to your account",
        "field_email"            to "EMAIL",
        "field_password"         to "PASSWORD",
        "field_code"             to "CODE FROM EMAIL",
        "field_totp"             to "CODE FROM APP",
        "placeholder_email"      to "you@example.com",
        "placeholder_password"   to "Your password",
        "placeholder_code"       to "000000",
        "btn_next"               to "Next",
        "btn_sign_in"            to "Sign in",
        "btn_continue"           to "Continue",
        "btn_confirm"            to "Confirm",
        "btn_close"              to "Close",
        "btn_try_again"          to "Try again",
        "btn_use_email_code"     to "Use code from email",
        "btn_use_password"       to "Use password",
        "btn_use_recovery"       to "Use recovery code",
        "btn_forgot"             to "Forgot password?",
        "btn_resend"             to "Resend code",
        "alt_divider"            to "or",
        "alt_qr"                 to "Sign in with QR code",
        "footer_no_account"      to "No account?",
        "footer_create"          to "Create one",
        "footer_have_account"    to "Have an account?",
        "footer_sign_in"         to "Sign in",
        "two_factor"             to "Two-factor authentication",
        "two_factor_hint"        to "Enter the 6-digit code from your authenticator app",
        "email_code_sent"        to "Code sent to",
        "loading_checking"       to "Checking\u2026",
        "loading_signing"        to "Signing in\u2026",
        "loading_sending"        to "Sending code\u2026",
        "loading_verifying"      to "Verifying\u2026",
        "btn_cancel_loading"     to "Cancel",
        "success_title"          to "Signed in",
        "error_invalid_email"    to "Enter a valid email address",
        "error_password_short"   to "Password must be at least 8 characters",
        "error_code_len"         to "Enter the 6-digit code",
        "err_title_network"      to "No network",
        "err_title_timeout"      to "Request timed out",
        "err_title_locked"       to "Account locked",
        "err_title_not_verified" to "Email not verified",
        "err_title_rate_limited" to "Too many attempts",
        "err_title_phishing"     to "Possible phishing detected",
        "err_title_server"       to "Server unavailable",
        "err_title_tls"          to "Secure connection failed",
        "err_title_storage"      to "Local storage failed",
        "err_title_config"       to "Configuration error",
        "err_title_oauth"        to "Authentication failed",
        "err_title_generic"      to "Something went wrong",
        "powered_by"             to "Powered by TOKEN PAY ID",
        "secure_badge"           to "TLS pinned",
        "passkey_title"          to "Sign in with passkey",
        "passkey_hint"           to "Use your fingerprint, face, or device PIN",
        "recovery_title"         to "Account recovery",
        "btn_send_recovery"      to "Send recovery email",
        "btn_back_signin"        to "Back to sign-in",
        // Sign-up
        "register_title"         to "Create your account",
        "register_hint"          to "This email isn't registered yet — fill in the form below to create a new account.",
        "register_code_sent"     to "Verification code sent to",
        "field_username"         to "USERNAME",
        "placeholder_username"   to "your_login",
        "hint_username"          to "Lowercase letters, digits, dots, underscores (3-30)",
        "placeholder_password_new" to "At least 8 characters",
        "btn_send_code"          to "Next",
        "btn_create_account"     to "Create account",
        "btn_resend_code"        to "Resend",
        "error_username_short"   to "Username must be at least 3 characters",
        "error_username_invalid" to "Lowercase letters, digits, dots and underscores only",
        "loading_creating"       to "Creating account…",
        // Self-update banner
        "update_available"       to "A newer TOKEN PAY ID version is available.",
        "btn_update_now"         to "Update",
        "btn_download_sdk"       to "Open SDK",
        "btn_update_later"       to "Later",
        "btn_retry"              to "Retry",
        // Smart updater phase labels (2.6.1) — banner morphs through
        // these in order; the Done state auto-dismisses after ~2.8 s.
        "update_checking"        to "Checking for updates…",
        "update_downloading"     to "Downloading %1${'$'}s / %2${'$'}s",
        "update_downloading_unknown" to "Downloading %1${'$'}s…",
        "update_verifying"       to "Verifying download…",
        "update_installing"      to "Installing…",
        "update_refreshing"      to "Applying new settings…",
        "update_done"            to "Updated to %1${'$'}s",
        "update_failed"          to "Update failed — please try again.",
        // QR login — 2.6.0: stopped lying about a non-existent
        // "TOKEN PAY mobile app". The real flow is: open id.tokenpay.space
        // on a device where the user is already signed in, and scan this
        // code with its built-in scanner.
        "qr_title"               to "Sign in with QR code",
        "qr_hint"                to "On a device where you are already signed in, open id.tokenpay.space and scan this code.",
        "qr_hint_secondary"      to "The scanner is in the sidebar on tokenpay.space and in the QR card on id.tokenpay.space/dashboard.",
        "qr_status_pending"      to "Waiting for confirmation…",
        "qr_status_approved"     to "Confirmed on your other device",
        "qr_status_expired"      to "QR code expired",
        "qr_status_error"        to "Couldn't start QR session",
        "qr_refresh"             to "Refresh",
        "qr_paste"               to "Paste QR link",
        "qr_paste_prompt"        to "Paste the tokenpay.space/qr-login?sid=… link",
        // Account memory (2.6.0)
        "welcome_continue_as"    to "Continue as %s",
        "remembered_session_hint" to "We'll check your saved session. If needed, we'll email a code.",
        "remembered_code_hint"    to "We'll email you a sign-in code.",
        "remembered_password_hint" to "You'll need your password and an email code.",
        "welcome_other_account" to "Use another account",
        "welcome_forget"         to "Forget this account",
    )

    private val ru = mapOf(
        "welcome_subtitle"       to "Единая система идентификации",
        "welcome_sign_in"        to "Войти",
        "welcome_create"         to "Создать аккаунт",
        "welcome_or"             to "или",
        "welcome_open_web"       to "Перейти на tokenpay.space",
        "signin_title"           to "Войдите в аккаунт",
        "field_email"            to "EMAIL",
        "field_password"         to "ПАРОЛЬ",
        "field_code"             to "КОД ИЗ ПИСЬМА",
        "field_totp"             to "КОД ИЗ ПРИЛОЖЕНИЯ",
        "placeholder_email"      to "you@example.com",
        "placeholder_password"   to "Ваш пароль",
        "placeholder_code"       to "000000",
        "btn_next"               to "Далее",
        "btn_sign_in"            to "Войти",
        "btn_continue"           to "Продолжить",
        "btn_confirm"            to "Подтвердить",
        "btn_close"              to "Закрыть",
        "btn_try_again"          to "Повторить",
        "btn_use_email_code"     to "Использовать код из письма",
        "btn_use_password"       to "Использовать пароль",
        "btn_use_recovery"       to "Код восстановления",
        "btn_forgot"             to "Забыли пароль?",
        "btn_resend"             to "Отправить повторно",
        "alt_divider"            to "или",
        "alt_qr"                 to "Войти по QR-коду",
        "footer_no_account"      to "Нет аккаунта?",
        "footer_create"          to "Создать",
        "footer_have_account"    to "Уже есть аккаунт?",
        "footer_sign_in"         to "Войти",
        "two_factor"             to "Двухфакторная аутентификация",
        "two_factor_hint"        to "Введите 6-значный код из приложения",
        "email_code_sent"        to "Код отправлен на",
        "loading_checking"       to "Проверяем\u2026",
        "loading_signing"        to "Входим\u2026",
        "loading_sending"        to "Отправляем код\u2026",
        "loading_verifying"      to "Проверяем код\u2026",
        "btn_cancel_loading"     to "Отмена",
        "success_title"          to "Вход выполнен",
        "error_invalid_email"    to "Введите корректный email",
        "error_password_short"   to "Пароль не менее 8 символов",
        "error_code_len"         to "Введите 6-значный код",
        "err_title_network"      to "Нет сети",
        "err_title_timeout"      to "Превышено время ожидания",
        "err_title_locked"       to "Аккаунт заблокирован",
        "err_title_not_verified" to "Email не подтверждён",
        "err_title_rate_limited" to "Слишком много попыток",
        "err_title_phishing"     to "Обнаружен фишинг",
        "err_title_server"       to "Сервер недоступен",
        "err_title_tls"          to "Ошибка защищённого соединения",
        "err_title_storage"      to "Ошибка локального хранилища",
        "err_title_config"       to "Ошибка конфигурации",
        "err_title_oauth"        to "Ошибка входа",
        "err_title_generic"      to "Что-то пошло не так",
        "powered_by"             to "Powered by TOKEN PAY ID",
        "secure_badge"           to "TLS защищён",
        "passkey_title"          to "Вход по passkey",
        "passkey_hint"           to "Отпечаток, Face ID или PIN устройства",
        "recovery_title"         to "Восстановление",
        "btn_send_recovery"      to "Отправить письмо",
        "btn_back_signin"        to "К форме входа",
        // Sign-up
        "register_title"         to "Создайте аккаунт",
        "register_hint"          to "Этот email ещё не зарегистрирован — заполните форму ниже, чтобы создать новый аккаунт.",
        "register_code_sent"     to "Код подтверждения отправлен на",
        "field_username"         to "ЛОГИН",
        "placeholder_username"   to "your_login",
        "hint_username"          to "Строчные буквы, цифры, точки, подчёркивания (3-30)",
        "placeholder_password_new" to "Минимум 8 символов",
        "btn_send_code"          to "Далее",
        "btn_create_account"     to "Создать аккаунт",
        "btn_resend_code"        to "Отправить ещё",
        "error_username_short"   to "Логин не менее 3 символов",
        "error_username_invalid" to "Только строчные латинские буквы, цифры, точка и подчёркивание",
        "loading_creating"       to "Создаём аккаунт…",
        // Self-update banner
        "update_available"       to "Доступна новая версия TOKEN PAY ID.",
        "btn_update_now"         to "Обновить",
        "btn_download_sdk"       to "Открыть SDK",
        "btn_update_later"       to "Позже",
        "btn_retry"              to "Повторить",
        // Фазы умного обновления (2.6.1).
        "update_checking"        to "Проверка обновлений…",
        "update_downloading"     to "Скачивание %1${'$'}s / %2${'$'}s",
        "update_downloading_unknown" to "Скачивание %1${'$'}s…",
        "update_verifying"       to "Проверка целостности…",
        "update_installing"      to "Установка…",
        "update_refreshing"      to "Применяем новые настройки…",
        "update_done"            to "Обновлено до %1${'$'}s",
        "update_failed"          to "Ошибка обновления — попробуйте позже.",
        // QR login — 2.6.0
        "qr_title"               to "Войти по QR-коду",
        "qr_hint"                to "На устройстве, где вы уже вошли, откройте id.tokenpay.space и отсканируйте этот код.",
        "qr_hint_secondary"      to "Сканер находится в боковой панели на tokenpay.space и в QR-блоке на id.tokenpay.space/dashboard.",
        "qr_status_pending"      to "Ожидаем подтверждения…",
        "qr_status_approved"     to "Подтверждено на другом устройстве",
        "qr_status_expired"      to "QR-код истёк",
        "qr_status_error"        to "Не удалось создать QR-сессию",
        "qr_refresh"             to "Обновить",
        "qr_paste"               to "Вставить ссылку",
        "qr_paste_prompt"        to "Вставьте ссылку tokenpay.space/qr-login?sid=…",
        // Account memory (2.6.0)
        "welcome_continue_as"    to "Продолжить как %s",
        "remembered_session_hint" to "Проверим сохранённый вход. Если нужно, пришлём код на почту.",
        "remembered_code_hint"    to "Пришлём код для входа на почту.",
        "remembered_password_hint" to "Понадобятся пароль и код из письма.",
        "welcome_other_account" to "Войти в другой аккаунт",
        "welcome_forget"         to "Забыть этот аккаунт",
    )

    private val zh = mapOf(
        "welcome_subtitle"       to "统一身份认证系统",
        "welcome_sign_in"        to "登录",
        "welcome_create"         to "注册账户",
        "welcome_or"             to "或",
        "welcome_open_web"       to "访问 tokenpay.space",
        "signin_title"           to "登录账户",
        "field_email"            to "邮箱",
        "field_password"         to "密码",
        "field_code"             to "邮件验证码",
        "field_totp"             to "应用验证码",
        "placeholder_email"      to "you@example.com",
        "placeholder_password"   to "您的密码",
        "placeholder_code"       to "000000",
        "btn_next"               to "下一步",
        "btn_sign_in"            to "登录",
        "btn_continue"           to "继续",
        "btn_confirm"            to "确认",
        "btn_close"              to "关闭",
        "btn_try_again"          to "重试",
        "btn_use_email_code"     to "使用邮件验证码",
        "btn_use_password"       to "使用密码",
        "btn_use_recovery"       to "使用恢复码",
        "btn_forgot"             to "忘记密码？",
        "btn_resend"             to "重新发送",
        "alt_divider"            to "或",
        "alt_qr"                 to "使用二维码登录",
        "footer_no_account"      to "没有账户？",
        "footer_create"          to "注册",
        "footer_have_account"    to "已有账户？",
        "footer_sign_in"         to "登录",
        "two_factor"             to "双因素认证",
        "two_factor_hint"        to "请输入应用中的6位验证码",
        "email_code_sent"        to "验证码已发送至",
        "loading_checking"       to "检查中\u2026",
        "loading_signing"        to "登录中\u2026",
        "loading_sending"        to "发送验证码\u2026",
        "loading_verifying"      to "验证中\u2026",
        "btn_cancel_loading"     to "取消",
        "success_title"          to "登录成功",
        "error_invalid_email"    to "请输入有效的邮箱",
        "error_password_short"   to "密码至少8个字符",
        "error_code_len"         to "请输入6位验证码",
        "err_title_network"      to "无网络连接",
        "err_title_timeout"      to "请求超时",
        "err_title_locked"       to "账户已锁定",
        "err_title_not_verified" to "邮箱未验证",
        "err_title_rate_limited" to "尝试次数过多",
        "err_title_phishing"     to "检测到钓鱼攻击",
        "err_title_server"       to "服务器不可用",
        "err_title_tls"          to "安全连接失败",
        "err_title_storage"      to "本地存储失败",
        "err_title_config"       to "配置错误",
        "err_title_oauth"        to "认证失败",
        "err_title_generic"      to "出错了",
        "powered_by"             to "由 TOKEN PAY ID 提供",
        "secure_badge"           to "TLS 绑定",
        "passkey_title"          to "使用密钥登录",
        "passkey_hint"           to "使用指纹、面容或设备 PIN",
        "recovery_title"         to "账户恢复",
        "btn_send_recovery"      to "发送恢复邮件",
        "btn_back_signin"        to "返回登录",
        // Sign-up
        "register_title"         to "创建您的账户",
        "register_hint"          to "此邮箱尚未注册 — 请填写以下表单创建新账户。",
        "register_code_sent"     to "验证码已发送至",
        "field_username"         to "用户名",
        "placeholder_username"   to "your_login",
        "hint_username"          to "小写字母、数字、点、下划线（3-30位）",
        "placeholder_password_new" to "至少8个字符",
        "btn_send_code"          to "下一步",
        "btn_create_account"     to "创建账户",
        "btn_resend_code"        to "重新发送",
        "error_username_short"   to "用户名至少3个字符",
        "error_username_invalid" to "仅限小写字母、数字、点和下划线",
        "loading_creating"       to "创建账户中…",
        // Self-update banner
        "update_available"       to "TOKEN PAY ID 新版本已发布。",
        "btn_update_now"         to "更新",
        "btn_download_sdk"       to "打开 SDK",
        "btn_update_later"       to "稍后",
        "btn_retry"              to "重试",
        // 智能更新的阶段标签 (2.6.1)。
        "update_checking"        to "检查更新中…",
        "update_downloading"     to "下载中 %1${'$'}s / %2${'$'}s",
        "update_downloading_unknown" to "下载中 %1${'$'}s…",
        "update_verifying"       to "校验文件中…",
        "update_installing"      to "正在安装…",
        "update_refreshing"      to "应用新配置…",
        "update_done"            to "已更新至 %1${'$'}s",
        "update_failed"          to "更新失败—请稍后重试。",
        // QR login — 2.6.0
        "qr_title"               to "二维码登录",
        "qr_hint"                to "在已登录的设备上，打开 id.tokenpay.space 并扫描此码。",
        "qr_hint_secondary"      to "扫描器位于 tokenpay.space 侧边栏和 id.tokenpay.space/dashboard 的 QR 卡片中。",
        "qr_status_pending"      to "等待确认…",
        "qr_status_approved"     to "已在另一设备上确认",
        "qr_status_expired"      to "二维码已过期",
        "qr_status_error"        to "无法创建二维码会话",
        "qr_refresh"             to "刷新",
        "qr_paste"               to "粘贴链接",
        "qr_paste_prompt"        to "请粘贴 tokenpay.space/qr-login?sid=… 链接",
        // Account memory (2.6.0)
        "welcome_continue_as"    to "继续使用 %s",
        "remembered_session_hint" to "将检查已保存的登录状态；如有需要，会发送邮箱验证码。",
        "remembered_code_hint"    to "我们会发送登录验证码到邮箱。",
        "remembered_password_hint" to "需要密码和邮箱验证码。",
        "welcome_other_account" to "使用其他账户",
        "welcome_forget"         to "忘记此账户",
    )
}
