import Foundation

/// Centralised UI strings for the native widget. Keep in sync with Android `Strings.kt`.
enum TpidStrings {

    static func resolveLanguage(_ pref: TpidConfig.Language) -> TpidConfig.Language {
        switch pref {
        case .system:
            let code: String
            if #available(iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0, *) {
                code = Locale.current.language.languageCode?.identifier ?? "en"
            } else {
                code = String(Locale.current.identifier.prefix(2)).lowercased()
            }
            switch code {
            case "ru": return .ru
            case "zh": return .zh
            default:   return .en
            }
        default:
            return pref
        }
    }

    static func of(_ lang: TpidConfig.Language) -> [String: String] {
        switch resolveLanguage(lang) {
        case .ru: return ru
        case .zh: return zh
        default:  return en
        }
    }

    private static let en: [String: String] = [
        "welcome_subtitle":       "Unified identification system",
        "welcome_sign_in":        "Sign in",
        "welcome_create":         "Create account",
        "welcome_or":             "or",
        "welcome_open_web":       "Open tokenpay.space",
        "signin_title":           "Sign in to your account",
        "field_email":            "EMAIL",
        "field_password":         "PASSWORD",
        "field_code":             "CODE FROM EMAIL",
        "field_totp":             "CODE FROM APP",
        "placeholder_email":      "you@example.com",
        "placeholder_password":   "Your password",
        "placeholder_code":       "000000",
        "btn_next":               "Next",
        "btn_sign_in":            "Sign in",
        "btn_continue":           "Continue",
        "btn_confirm":            "Confirm",
        "btn_close":              "Close",
        "btn_try_again":          "Try again",
        "btn_use_email_code":     "Use code from email",
        "btn_use_password":       "Use password",
        "btn_use_recovery":       "Use recovery code",
        "btn_forgot":             "Forgot password?",
        "btn_resend":             "Resend code",
        "alt_divider":            "or",
        "alt_qr":                 "Sign in with QR code",
        "footer_no_account":      "No account?",
        "footer_create":          "Create one",
        "footer_have_account":    "Have an account?",
        "footer_sign_in":         "Sign in",
        "two_factor":             "Two-factor authentication",
        "two_factor_hint":        "Enter the 6-digit code from your authenticator app",
        "email_code_sent":        "Code sent to",
        "loading_checking":       "Checking…",
        "loading_signing":        "Signing in…",
        "loading_sending":        "Sending code…",
        "loading_verifying":      "Verifying…",
        "success_title":          "Signed in",
        "error_invalid_email":    "Enter a valid email address",
        "error_password_short":   "Password must be at least 8 characters",
        "error_code_len":         "Enter the 6-digit code",
        "err_title_network":      "No network",
        "err_title_timeout":      "Request timed out",
        "err_title_locked":       "Account locked",
        "err_title_not_verified": "Email not verified",
        "err_title_rate_limited": "Too many attempts",
        "err_title_phishing":     "Possible phishing detected",
        "err_title_server":       "Server unavailable",
        "err_title_config":       "Configuration error",
        "err_title_oauth":        "Authentication failed",
        "err_title_generic":      "Something went wrong",
        "powered_by":             "Powered by TOKEN PAY ID",
        "secure_badge":           "TLS pinned",
        "passkey_title":          "Sign in with passkey",
        "passkey_hint":           "Use Face ID, Touch ID, or device passcode",
        "recovery_title":         "Account recovery",
        "btn_send_recovery":      "Send recovery email",
        "btn_back_signin":        "Back to sign-in",
        // Sign-up
        "register_title":         "Create your account",
        "register_hint":          "This email isn't registered yet — fill in the form below to create a new account.",
        "register_code_sent":     "Verification code sent to",
        "field_username":         "USERNAME",
        "placeholder_username":   "your_login",
        "hint_username":          "Lowercase letters, digits, dots, underscores (3-30)",
        "placeholder_password_new": "At least 8 characters",
        "btn_send_code":          "Next",
        "btn_create_account":     "Create account",
        "btn_resend_code":        "Resend",
        "error_username_short":   "Username must be at least 3 characters",
        "error_username_invalid": "Lowercase letters, digits, dots and underscores only",
        "qr_paste":               "Paste QR link",
        "qr_paste_prompt":        "Paste the tokenpay.space/qr-login?sid=… link",
        "update_available":       "A newer TOKEN PAY ID version is available.",
        "btn_update_now":         "Update",
        "btn_download_sdk":       "Open SDK",
        "btn_update_later":       "Later",
        "btn_retry":              "Retry",
        // Smart updater phase labels (2.6.1). Banner morphs through these
        // in order; the Done state auto-dismisses after ~2.8 s.
        "update_checking":        "Checking for updates…",
        "update_downloading":     "Downloading %1$@ / %2$@",
        "update_downloading_unknown": "Downloading %1$@…",
        "update_verifying":       "Verifying download…",
        "update_installing":      "Installing…",
        "update_refreshing":      "Applying new settings…",
        "update_done":            "Updated to %1$@",
        "update_failed":          "Update failed — please try again.",
        // Account memory (2.6.0)
        "welcome_continue_as":    "Continue as %@",
        "remembered_session_hint": "We'll check your saved session. If needed, we'll email a code.",
        "remembered_code_hint":    "We'll email you a sign-in code.",
        "remembered_password_hint": "You'll need your password and an email code.",
        "welcome_other_account":  "Use another account",
        "welcome_forget":         "Forget this account",
        // QR login — 2.6.0 rewrite, no non-existent mobile app
        "qr_title":               "Sign in with QR code",
        "qr_hint":                "On a device where you are already signed in, open id.tokenpay.space and scan this code.",
        "qr_hint_secondary":      "The scanner is in the sidebar on tokenpay.space and in the QR card on id.tokenpay.space/dashboard.",
        "qr_status_pending":      "Waiting for confirmation…",
        "qr_status_approved":     "Confirmed on your other device",
        "qr_status_expired":      "QR code expired",
        "qr_status_error":        "Couldn't start QR session",
        "qr_refresh":             "Refresh",
        "loading_creating":       "Creating account…",
    ]

    private static let ru: [String: String] = [
        "welcome_subtitle":       "Единая система идентификации",
        "welcome_sign_in":        "Войти",
        "welcome_create":         "Создать аккаунт",
        "welcome_or":             "или",
        "welcome_open_web":       "Перейти на tokenpay.space",
        "signin_title":           "Войдите в аккаунт",
        "field_email":            "EMAIL",
        "field_password":         "ПАРОЛЬ",
        "field_code":             "КОД ИЗ ПИСЬМА",
        "field_totp":             "КОД ИЗ ПРИЛОЖЕНИЯ",
        "placeholder_email":      "you@example.com",
        "placeholder_password":   "Ваш пароль",
        "placeholder_code":       "000000",
        "btn_next":               "Далее",
        "btn_sign_in":            "Войти",
        "btn_continue":           "Продолжить",
        "btn_confirm":            "Подтвердить",
        "btn_close":              "Закрыть",
        "btn_try_again":          "Повторить",
        "btn_use_email_code":     "Использовать код из письма",
        "btn_use_password":       "Использовать пароль",
        "btn_use_recovery":       "Код восстановления",
        "btn_forgot":             "Забыли пароль?",
        "btn_resend":             "Отправить повторно",
        "alt_divider":            "или",
        "alt_qr":                 "Войти по QR-коду",
        "footer_no_account":      "Нет аккаунта?",
        "footer_create":          "Создать",
        "footer_have_account":    "Уже есть аккаунт?",
        "footer_sign_in":         "Войти",
        "two_factor":             "Двухфакторная аутентификация",
        "two_factor_hint":        "Введите 6-значный код из приложения",
        "email_code_sent":        "Код отправлен на",
        "loading_checking":       "Проверяем…",
        "loading_signing":        "Входим…",
        "loading_sending":        "Отправляем код…",
        "loading_verifying":      "Проверяем код…",
        "success_title":          "Вход выполнен",
        "error_invalid_email":    "Введите корректный email",
        "error_password_short":   "Пароль не менее 8 символов",
        "error_code_len":         "Введите 6-значный код",
        "err_title_network":      "Нет сети",
        "err_title_timeout":      "Превышено время ожидания",
        "err_title_locked":       "Аккаунт заблокирован",
        "err_title_not_verified": "Email не подтверждён",
        "err_title_rate_limited": "Слишком много попыток",
        "err_title_phishing":     "Обнаружен фишинг",
        "err_title_server":       "Сервер недоступен",
        "err_title_config":       "Ошибка конфигурации",
        "err_title_oauth":        "Ошибка входа",
        "err_title_generic":      "Что-то пошло не так",
        "powered_by":             "Powered by TOKEN PAY ID",
        "secure_badge":           "TLS защищён",
        "passkey_title":          "Вход по passkey",
        "passkey_hint":           "Face ID, Touch ID или пароль устройства",
        "recovery_title":         "Восстановление",
        "btn_send_recovery":      "Отправить письмо",
        "btn_back_signin":        "К форме входа",
        // Sign-up
        "register_title":         "Создайте аккаунт",
        "register_hint":          "Этот email ещё не зарегистрирован — заполните форму ниже, чтобы создать новый аккаунт.",
        "register_code_sent":     "Код подтверждения отправлен на",
        "field_username":         "ЛОГИН",
        "placeholder_username":   "your_login",
        "hint_username":          "Строчные буквы, цифры, точки, подчёркивания (3-30)",
        "placeholder_password_new": "Минимум 8 символов",
        "btn_send_code":          "Далее",
        "btn_create_account":     "Создать аккаунт",
        "btn_resend_code":        "Отправить ещё",
        "error_username_short":   "Логин не менее 3 символов",
        "error_username_invalid": "Только строчные латинские буквы, цифры, точка и подчёркивание",
        "qr_paste":               "Вставить ссылку",
        "qr_paste_prompt":        "Вставьте ссылку tokenpay.space/qr-login?sid=…",
        "update_available":       "Доступна новая версия TOKEN PAY ID.",
        "btn_update_now":         "Обновить",
        "btn_download_sdk":       "Открыть SDK",
        "btn_update_later":       "Позже",
        "btn_retry":              "Повторить",
        // Фазы умного обновления (2.6.1).
        "update_checking":        "Проверка обновлений…",
        "update_downloading":     "Скачивание %1$@ / %2$@",
        "update_downloading_unknown": "Скачивание %1$@…",
        "update_verifying":       "Проверка целостности…",
        "update_installing":      "Установка…",
        "update_refreshing":      "Применяем новые настройки…",
        "update_done":            "Обновлено до %1$@",
        "update_failed":          "Ошибка обновления — попробуйте позже.",
        // Account memory (2.6.0)
        "welcome_continue_as":    "Продолжить как %@",
        "remembered_session_hint": "Проверим сохранённый вход. Если нужно, пришлём код на почту.",
        "remembered_code_hint":    "Пришлём код для входа на почту.",
        "remembered_password_hint": "Понадобятся пароль и код из письма.",
        "welcome_other_account":  "Войти в другой аккаунт",
        "welcome_forget":         "Забыть этот аккаунт",
        // QR login — 2.6.0 rewrite
        "qr_title":               "Войти по QR-коду",
        "qr_hint":                "На устройстве, где вы уже вошли, откройте id.tokenpay.space и отсканируйте этот код.",
        "qr_hint_secondary":      "Сканер находится в боковой панели на tokenpay.space и в QR-блоке на id.tokenpay.space/dashboard.",
        "qr_status_pending":      "Ожидаем подтверждения…",
        "qr_status_approved":     "Подтверждено на другом устройстве",
        "qr_status_expired":      "QR-код истёк",
        "qr_status_error":        "Не удалось создать QR-сессию",
        "qr_refresh":             "Обновить",
        "loading_creating":       "Создаём аккаунт…",
    ]

    private static let zh: [String: String] = [
        "welcome_subtitle":       "统一身份认证系统",
        "welcome_sign_in":        "登录",
        "welcome_create":         "注册账户",
        "welcome_or":             "或",
        "welcome_open_web":       "访问 tokenpay.space",
        "signin_title":           "登录账户",
        "field_email":            "邮箱",
        "field_password":         "密码",
        "field_code":             "邮件验证码",
        "field_totp":             "应用验证码",
        "placeholder_email":      "you@example.com",
        "placeholder_password":   "您的密码",
        "placeholder_code":       "000000",
        "btn_next":               "下一步",
        "btn_sign_in":            "登录",
        "btn_continue":           "继续",
        "btn_confirm":            "确认",
        "btn_close":              "关闭",
        "btn_try_again":          "重试",
        "btn_use_email_code":     "使用邮件验证码",
        "btn_use_password":       "使用密码",
        "btn_use_recovery":       "使用恢复码",
        "btn_forgot":             "忘记密码？",
        "btn_resend":             "重新发送",
        "alt_divider":            "或",
        "alt_qr":                 "使用二维码登录",
        "footer_no_account":      "没有账户？",
        "footer_create":          "注册",
        "footer_have_account":    "已有账户？",
        "footer_sign_in":         "登录",
        "two_factor":             "双因素认证",
        "two_factor_hint":        "请输入应用中的6位验证码",
        "email_code_sent":        "验证码已发送至",
        "loading_checking":       "检查中…",
        "loading_signing":        "登录中…",
        "loading_sending":        "发送验证码…",
        "loading_verifying":      "验证中…",
        "success_title":          "登录成功",
        "error_invalid_email":    "请输入有效的邮箱",
        "error_password_short":   "密码至少8个字符",
        "error_code_len":         "请输入6位验证码",
        "err_title_network":      "无网络连接",
        "err_title_timeout":      "请求超时",
        "err_title_locked":       "账户已锁定",
        "err_title_not_verified": "邮箱未验证",
        "err_title_rate_limited": "尝试次数过多",
        "err_title_phishing":     "检测到钓鱼攻击",
        "err_title_server":       "服务器不可用",
        "err_title_config":       "配置错误",
        "err_title_oauth":        "认证失败",
        "err_title_generic":      "出错了",
        "powered_by":             "由 TOKEN PAY ID 提供",
        "secure_badge":           "TLS 绑定",
        "passkey_title":          "使用密钥登录",
        "passkey_hint":           "使用 Face ID、Touch ID 或设备密码",
        "recovery_title":         "账户恢复",
        "btn_send_recovery":      "发送恢复邮件",
        "btn_back_signin":        "返回登录",
        // Sign-up
        "register_title":         "创建您的账户",
        "register_hint":          "此邮箱尚未注册 — 请填写以下表单创建新账户。",
        "register_code_sent":     "验证码已发送至",
        "field_username":         "用户名",
        "placeholder_username":   "your_login",
        "hint_username":          "小写字母、数字、点、下划线（3-30位）",
        "placeholder_password_new": "至少8个字符",
        "btn_send_code":          "下一步",
        "btn_create_account":     "创建账户",
        "btn_resend_code":        "重新发送",
        "error_username_short":   "用户名至少3个字符",
        "error_username_invalid": "仅限小写字母、数字、点和下划线",
        "qr_paste":               "粘贴链接",
        "qr_paste_prompt":        "请粘贴 tokenpay.space/qr-login?sid=… 链接",
        "update_available":       "TOKEN PAY ID 新版本已发布。",
        "btn_update_now":         "更新",
        "btn_download_sdk":       "打开 SDK",
        "btn_update_later":       "稍后",
        "btn_retry":              "重试",
        // 智能更新的阶段标签 (2.6.1)。
        "update_checking":        "检查更新中…",
        "update_downloading":     "下载中 %1$@ / %2$@",
        "update_downloading_unknown": "下载中 %1$@…",
        "update_verifying":       "校验文件中…",
        "update_installing":      "正在安装…",
        "update_refreshing":      "应用新配置…",
        "update_done":            "已更新至 %1$@",
        "update_failed":          "更新失败—请稍后重试。",
        // Account memory (2.6.0)
        "welcome_continue_as":    "继续使用 %@",
        "remembered_session_hint": "将检查已保存的登录状态；如有需要，会发送邮箱验证码。",
        "remembered_code_hint":    "我们会发送登录验证码到邮箱。",
        "remembered_password_hint": "需要密码和邮箱验证码。",
        "welcome_other_account":  "使用其他账户",
        "welcome_forget":         "忘记此账户",
        // QR login — 2.6.0 rewrite
        "qr_title":               "二维码登录",
        "qr_hint":                "在已登录的设备上，打开 id.tokenpay.space 并扫描此码。",
        "qr_hint_secondary":      "扫描器位于 tokenpay.space 侧边栏和 id.tokenpay.space/dashboard 的 QR 卡片中。",
        "qr_status_pending":      "等待确认…",
        "qr_status_approved":     "已在另一设备上确认",
        "qr_status_expired":      "二维码已过期",
        "qr_status_error":        "无法创建二维码会话",
        "qr_refresh":             "刷新",
        "loading_creating":       "创建账户中…",
    ]
}
